# Generated by Django 4.2.9 on 2024-01-22 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_alter_propertyimages_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PropertyImages',
        ),
    ]
